version: "3.8"

services:
  app:
    build:
      context: .
    container_name: wildberries_api_bot
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:pa$$word@db:5432/wildberries
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: wildberries_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wildberries
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
