version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db/project_db
    volumes:
      - .:/app

  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - TELEGRAM_API_TOKEN=your-telegram-token
      - DATABASE_URL=postgresql+asyncpg://user:password@db/project_db
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
